// <auto-generated />
namespace WebRole1.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class stilltestingonmevm : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(stilltestingonmevm));
        
        string IMigrationMetadata.Id
        {
            get { return "201901261229498_still testing on me vm"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
