// <auto-generated />
namespace WebRole1.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class tryingtofixmevm : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(tryingtofixmevm));
        
        string IMigrationMetadata.Id
        {
            get { return "201901270602285_trying to fix me vm"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
