// <auto-generated />
namespace WebRole1.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class testingmedicalequipmentindex : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(testingmedicalequipmentindex));
        
        string IMigrationMetadata.Id
        {
            get { return "201901260757472_testing medical equipment index"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
